---
title: "Atelier 4"
author: "Charlotte Rondeau"
date: "13/11/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

(voir ctrl+alt+i = magique)
$= "en fonction de"

## Option 1

```{r}
nutriage <- read.csv("~/cours CEU/biostat/ateliers/Atelier4-master (2)/Atelier4-master/nutriage.csv")
names(nutriage)
```


```{r}
hist(nutriage$taille)
summary(nutriage$taille)
```

H: taille $\sim N(\mu,\sigma)$ le problème est $\Pr(taille<0) >0$

```{r}
mean(nutriage$taille)
sd(nutriage$taille)
```

On va calculer $\Pr(taille < 0)$ avec $taille \sim N(163.9602,9.003368)$

```{r}
pnorm(0,mean(nutriage$taille),sd(nutriage$taille))
```

## Option 2 

Soit $taille = e^X$ avec $X \sim N(\mu,\sigma)$ alors $X = ln(taille).$

```{r}
X <- log(nutriage$taille)
hist(X)
summary(X)
Q <- seq(from=0,to=1,by=0.1)
Q
qnorm(Q)

```

qq-plot


```{r}
Z <- (X-mean(X))/sd(X)
n <- length(Z)
n
Normal <- rnorm(n)
qqplot(Normal,Z,xlim=c(-3,3),ylim=c(-3,3))
par(new=T)
plot(Z,Z,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3),xlabel="",ylabel="")
```

## poids 


```{r}
hist(nutriage$poids)
summary(nutriage$poids)
```




```{r}
mean(nutriage$poids)
sd(nutriage$poids)
```



```{r}
pnorm(0,mean(nutriage$poids),sd(nutriage$poids))
```




```{r}
X <- log(nutriage$poids)
hist(X)
summary(X)
Q <- seq(from=0,to=1,by=0.1)
Q
qnorm(Q)

```

qq-plot


```{r}
Z <- (X-mean(X))/sd(X)
n <- length(Z)
n
Normal <- rnorm(n)
qqplot(Normal,Z,xlim=c(-3,3),ylim=c(-3,3),xlab = "Normal",ylab="log(poids)")
par(new=T)
plot(Z,Z,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3),xlab="",ylab="")
```

cafe
```{r}
table(nutriage$cafe)
mean(nutriage$cafe)
var(nutriage$cafe)
lambda <- (mean(nutriage$cafe)+var(nutriage$cafe))/2
lambda
simul <- rpois(1000,lambda)
table(simul)
```


the

```{r}
table(nutriage$the)
mean(nutriage$the)
var(nutriage$the)
lambda <- (mean(nutriage$the)+var(nutriage$the))/2
lambda
simul <- rpois(1000,lambda)
table(simul)
```









